version: '3.9'

services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
    command: celery -A shop_api worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  celery_beat:
    build:
      context: .
    command: celery -A shop_api beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  celery_flower:
    build:
      context: .
    command: celery -A shop_api flower --port=5555
    ports:
      - "5556:5555"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  db-data:
  redis_data:
